### ISSUE TITLE
INFCubeFlyThatShouldStillBypass no longer bypasses

### ISSUE THREAD

**Issue by EthoIRL** [True-cc/Scripts#1]

**Comment by SelfMadeSystem** [comment]
fuck off please thx

**Comment by SelfMadeSystem** [comment]
this is dead please stop

**Comment by EthoIRL** [comment]
why do you want to fuck me?

**Comment by SelfMadeSystem** [comment]
I didn't say "fuck me", I said "fuck off". There is a substantial difference between the two phrases.
